---

ansible_user: dwijeshm3

ansible_password: 

ansible_connection: winrm

ansible_winrm_server_cert_validation: ignore

ansible_winrm_transport: basic

ansible_winrm_port: 5986

ansible_python_interpreter: C:\Users\dwijeshm3\AppData\Local\Programs\Python\Python37\python

